import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter, Lato, Oswald } from "next/font/google";
import "./globals.css";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const oswaldFont = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const latoFont = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          interFont.variable,
          oswaldFont.variable,
          latoFont.variable,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
